name: Firebase Deploye

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v4

      - name: Install Node 
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: yarn

      - name: Install Dependecies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Build 
        run: yarn build

      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}